name: "publish"

on:
  workflow_dispatch:
    inputs:
      build_windows:
        type: boolean
        default: true
        description: "Build Windows"
      build_linux:
        type: boolean
        default: true
        description: "Build Linux"
      build_mac:
        type: boolean
        default: true
        description: "Build Mac ARM"
      build_mac_intel:
        type: boolean
        default: true
        description: "Build Mac x86_64 Intel"
      build_android:
        type: boolean
        default: true
        description: "Build Android APK"
  push:
    tags:
      - "v*.*.*"

# This workflow will trigger on each push to the `release` branch to create or update a GitHub release, build your app, and upload the artifacts to the release.

jobs:
  publish-tauri-android:
    name: Publish Android
    if: ${{ inputs.build_android }}
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - name: Install WASM Rust Target
        run: rustup target add wasm32-unknown-unknown

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: sdkmanager --install "ndk;27.2.12479018"

      - name: Install Android Rust Targets
        run: rustup target add aarch64-linux-android armv7-linux-androideabi i686-linux-android x86_64-linux-android

      - name: Setup Tauri CLI
        run: npm install -g @tauri-apps/cli@latest

      - name: Run Tauri Build
        env:
          NDK_HOME: /usr/local/lib/android/sdk/ndk/27.2.12479018
        run: npx tauri android build --split-per-abi

  publish-tauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "MacOS ARM"
            platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - name: "MacOS x64"
            platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - name: "Ubuntu"
            platform: "ubuntu-latest"
            args: ""
          - name: "Windows"
            platform: "windows-latest"
            args: ""

    name: "Publish ${{ matrix.name }}"
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Dependencies (Ubuntu Only)
        if: matrix.name == 'Ubuntu'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libasound2-dev

      - name: Install Dependencies (MacOS Only)
        if: matrix.platform == 'macos-latest'
        run: |
          brew update
          brew install --force openssl@3
          brew link --force openssl@3

      - name: Install Trunk
        uses: jetli/trunk-action@v0.5.0
        with:
          version: "v0.21.4"

      - name: Install WASM Rust Target
        run: rustup target add wasm32-unknown-unknown

      - name: Run Tauri Build
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: "./gui"
          # tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version.
          # releaseName: "App v__VERSION__"
          # releaseBody: "See the assets to download this version and install."
          # releaseDraft: true
          # prerelease: false
          args: ${{ matrix.args }}
